development:

MAILCHIMP_API_KEY:    'c284fbe65042041a051c748a15b10073-us13'
MAILCHIMP_LIST_ID:    'd12778a49a'

production:

MAILCHIMP_API_KEY:    'c284fbe65042041a051c748a15b10073-us13'
MAILCHIMP_LIST_ID:    'd12778a49a'

POSTMARK_API_TOKEN:   '54720f7c-7ab0-45f8-8e8c-4fdd0cbd53e0'
DEV_EMAIL:            'hello@flykke.com'

HOST: 'flykkelp.herokuapp.com'

